name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run tests
    - name: Run unit tests
      env:
        MODE: test  # Example environment variable
      run: |
        python -m unittest discover -s app -p "*.py"

    # Code quality checks (optional)
    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 app --max-line-length=88 --exclude=__init__.py
